<?php include 'parts/head.php' ?>
        <title>mvt3am - KSP Mods</title>
        <?php include 'parts/head_scripts.php'?>
    </head>
    <body>
    <div class="fh5co-loader"></div>
    <div id="fh5co-page">
        <nav id="fh5co-nav" role="navigation">
            <ul>
                <li class="animate-box"><a href="home" class="transition">Home</a></li>
                <li class="animate-box"><a href="stream" class="transition">Stream</a></li>
                <li class="animate-box"><a href="contest" class="transition">Contest</a></li>
                <li class="animate-box"><a href="about" class="transition">Bio</a></li>
            </ul>
        </nav>
        <header id="fh5co-header" role="banner" class="fh5co-project js-fh5co-waypoint no-border" data-colorbg="#222222" data-next="yes">
            <div class="container">
                <div class="fh5co-text-wrap animate-box">
                    <div class="fh5co-intro-text">
                        <h1>Kerbal Space Program <br><span>mods</span></h1>
                    </div>
                </div>
            </div>
            <div class="btn-next animate-box fh5co-learn-more">
                <a href="#" class="scroll-btn">
                    <span>See the detail</span>
                    <i class="icon-chevron-down"></i>
                </a>
            </div>
        </header>
        <div class="js-fh5co-waypoint fh5co-project-detail" id="fh5co-main" data-colorbg="">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="row row-bottom-padded-sm animate-box">
                            <div class="col-md-3">
                                <h3 class="fh5co-section-heading"><span class="fh5co-number">N<sup>o</sup> 1</span> Mods
                                </h3>
                            </div>
                            <div class="col-md-9">
                                <p class="fh5co-lead">
                                    Kerbal Space Program <sub>v</sub>1.11.1.
                                    <br>
                                    Attention! Are not 100% all the mods because some are been downloaded directly from <a href="https://forum.kerbalspaceprogram.com">ksp forum</a> or <a href="https://www.github.com">github</a> and are not exist in this list.
                                    <br>
                                    <h4>The list will updated weekly from CKAN</h4>
                                </p>
                                <div class="mods_list">
                                    <pre>
Flight Manager for Reusable Stages (FMRS) Continued (FMRSContinued 1.2.9.1)
AIES Aerospace (AIESAerospace-Unofficial 1.6.1-patched)
AIES Patches for the AIES Aerospace mod (AIES-Patches 0.0.1.3)
AlphaMensae's Modular Launch Pads (ModularLaunchPads 2.1.2)
Angara (AngaraRocketPack v2.0)
Animated Attachment (AnimatedAttachment v2.1.5)
Animated Decouplers (AnimatedDecouplers v1.4.2.2)
Antares-Cygnus (AntaresCygnus 1:v1.8)
Antenna Patches from @DeimosRast for the AIES-Patches mod (AIES-DeimosRast 0.0.1.3)
ASET Agency  (ASETAgency 1.0)
ASET Avionics (ASETAvionics 2.1)
ASET PRC (Portable Rover Components) (ASET-PRC 0.1.0.1)
ASET Props (ASETProps 1.5)
Astrogator (Astrogator v0.10.2)
Astronomer's Visual Pack (AstronomersVisualPack 2:v4.05)
Astronomer's Visual Pack-4k Textures (AVP-4kTextures v1.11)
AT Utils (AT-Utils v1.9.6)
AtmosphereAutopilot (Fly-By-Wire) (AtmosphereAutopilot v1.5.16)
Austrian Space Agency (AustrianSpaceAgency 1.1.1)
Aviation Lights (AviationLights 1:v4.1.1)
B9 Aerospace Props (B9-props 1:v6.6.0)
B9 Animation Modules (B9AnimationModules v1.7.0)
B9 Part Switch (B9PartSwitch v2.17.0)
BahamutoD Animation Modules (BDAnimationModules 1:v0.6.6.0)
BARIS Bridge (BarisBridge v1.10)
BDB Now in Colors! (TantaresAndBDBNowinColors 2.0)
Better Order of Parts: Numbered  (BOPN) (BOPN 3.1)
Better SR Bs (BetterSRBs 1.2.4)
Blockland Space Program Flag (BlocklandSpaceProgramFlag v0)
Bluedog Design Bureau (BluedogDB v1.7.1)
Bob's Panic Box (BobsPanicBox 1:0.0.2.3)
BOMPs (BOMPs 1.0.2)
Brazilian Flag - Bandeira do Brasil (BrazilianFlagBandeiradoBrasil 2.0)
BreakingGround-DLC (BreakingGround-DLC (unmanaged))
CCTV (CCTV 1.1.6.5)
Chatterer (Chatterer 0.9.99)
Chatterer Extended (ChattererExtended 0.6.2)
Chrayol Design Org. (ChayrolDesignOrg v1.0)
ClickThrough Blocker (ClickThroughBlocker 1:0.1.10.15)
CommNet Antennas Extension (CommNetAntennasExtension 2.1.4)
CommNet Manager (CommNetManager 1.1.0)
Community Category Kit (CommunityCategoryKit v5.2.0.0)
Community Resource Pack (CommunityResourcePack 1.4.2)
Community Tech Tree (CommunityTechTree 1:3.4.3)
Configurable Containers (ConfigurableContainers 2.6.1)
Connected Living Space (ConnectedLivingSpace 2.0.0.6)
Constellation Essentials (ConstellationEssentials v1.4.1.0)
Contares Common (Contares-Common 1.8.9)
Contract Configurator (ContractConfigurator 1.30.5)
Craft Manager (CraftManager 1.2.0)
Crew R&R (CrewQueueTwo 1.1.11)
Cryo Tanks (CryoTanks 1.5.6)
Cryo Tanks Core (CryoTanks-Core 1.5.6)
Cryogenic Engines (CryoEngines 1:1.2.1)
Custom Pre Lauch Checks (CustomPreLaunchChecks 1.8.1)
Deadly Reentry Continued (DeadlyReentry v7.8.0)
Deep Space Surface Habitat Unit Pack (DeepSpaceSurfaceHabitatUnitPack 1.10.1)
Deployable Engines Plugin (DeployableEngines 1.2.3)
Distant Object Enhancement Continued (DistantObject v2.0.2.0)
Distant Object Enhancement Continued default config (DistantObject-default v2.0.2.0)
DMagic Orbital Science (DMagicOrbitalScience 1.4.3)
DMModuleScienceAnimateGeneric (DMagicScienceAnimate v0.23)
Docking Cam (DockingCamKURS 1.3.8)
Docking Port Sound FX (DockingPortSoundFX v2.1.12)
Dodo Labs - Stockalike Electron (DodoLabsStockalikeElectron 1.3.1.1)
DSEV (DSEV v3.7.1)
DSEV CRP Play Mode (DSEV-PlayMode-CRP v3.7.1)
Duna Direct (DunaDirect 1.10.1)
Duna Incubator's Habitat (DunaIncubatorHabitat 0.0.2)
DuoPods (DuoPods 1.0.2.0)
Dynamic Battery Storage (DynamicBatteryStorage 2:2.2.1.0)
Earn Your Stripes! (EarnYourStripes 4.0.2)
Environmental Visual Enhancements Redux (EnvironmentalVisualEnhancements 3:1.11.2.1)
EVA Handrails Continued (EVAHandrailsPackContinued 0.3.0.3)
EVA Parachutes & Ejection Seats (EVAParachutes 0.2.0.2)
EVA Refueling (EVARefueling 0.0)
EVA Struts (EVAStruts 6.0)
Extraplanetary Launchpads (ExtraPlanetaryLaunchpads 6.8.3.0)
FASA (FASA 1:v7.2.6)
Federal Productions Flags (FederalProductions-Flags 0.2)
Filter Extensions - Plugin (FilterExtensions 3.2.6)
Firespitter Core (FirespitterCore v7.17)
Flag Pack (FlagPack v1.1.1)
Flight Tracker (FlightTracker 3.0.0.1)
Fuel Tanks Plus (FuelTanksPlus 2.0.2)
Global Construction (GroundConstruction 2.6.4.1)
Global Construction Core (GroundConstruction-Core 2.6.4.1)
Hangar Extender (HangerExtenderExtended 3.6.0)
HullcamVDS Continued (HullcamVDSContinued 0.2.0.1)
HyperEdit (HyperEdit 1.5.8.0)
IndicatorLights (IndicatorLights 1.7)
Infernal RO-Robotics (InfernalRoboticsRealismOverhaul 2.3.1)
ION RCS (IONRCS V0.1.10.0)
James Webb For Kerbal (JamesWebbForKerbal 1.9.x1.10.LTE)
JSat (JSat 1.8.1.2)
JSIPartUtilities (JSIPartUtilities 0.5.0.4)
JX2Antenna (JX2Antenna 2.0.5)
KeR-7 (KeR-7 1.0)
Kerbal Actuators (KerbalActuators v1.8.3)
Kerbal Atomics (KerbalAtomics 1:1.2.1)
Kerbal Attachment System (KAS 1.7)
Kerbal Changelog (KerbalChangelog v1.3.0)
Kerbal Engineer Redux (KerbalEngineerRedux 1.1.8.3)
Kerbal GPS (KerbalGPSRevived 1.2.1)
Kerbal Inventory for All (KerbalInventoryForAll 1:1.2.1)
Kerbal Inventory System (KIS 1.28)
Kerbal Joint Reinforcement Continued (KerbalJointReinforcementContinued v3.5.2)
Kerbal NRAP - Procedural Test Weights (KerbalNRAP 1.6.0)
Kerbal Reusability Expansion (SpaceXLegs 2.9.1)
Kerbal Tubes (KerbalTubes 1.3.3.3)
Kerbalism (Kerbalism 3.12)
Kerbalism - Default Config (Kerbalism-Config-Default 3.12)
Kerbalized SpaceX (Kerbalized-SpaceX 1.26)
Kerbal-Konstructs (KerbalKonstructs 1.8.1.15)
Kerbin Side Remastered (KerbinSideRemastered 1.0.1)
Kethane Mining (Kethane 0.10.3)
KipDockingPorts (KipDockingPorts v0.2)
KipEng Agency (KipEng-Agency v0.2)
Konstruction (Konstruction 1.4.0)
KSC Extended (KSCExtended 2.2)
KSI Wheels (KSIWheels 0.0.1)
KSP AVC (KSP-AVC 1.4.1.5)
KSP Wheel (KSPWheel 1:0.16.14.33)
KW Rocketry Rebalanced (KWRocketryRebalanced 3.2.7.2)
KXAPI (KXAPI 1.2.0)
Landertrons (Landertron v1.2.0)
Launch Escape System (PEBKACIndustriesLaunchEscapeSystem 1:1.4.2)
LCD - Launch CountDown (LCDLaunchCountDown 1.8.0)
Lithobrake Exploration Technologies (LithobrakeExplorationTechnologies 0.4)
LoadingTipsPlus (LoadingTipsPlus V1.9)
Magpie Mods (MagpieMods 1.5.9)
Making History (MakingHistory-DLC 1.11.0)
Mark IV Spaceplane System (MarkIVSpaceplaneSystem 3.2.0)
MechJeb 2 - DEV RELEASE (MechJeb2-dev 2.12.0.0-1042)
MechJeb and Engineer for all! (MechJebForAll 1.3.0.6)
MemGraph (MemGraph 1:1.2.0)
Missing Robotics (MissingRobotics 1)
Mkerb Inc. Science Instruments (MkerbIncScienceInstruments 1.1)
Modular Rocket Systems (ModularRocketSystem 1.13.2)
Modular Segmented SRBs (MS-SRBs 0.0.2.1)
ModularFlightIntegrator (ModularFlightIntegrator 1.2.9.0)
Module Manager (ModuleManager 4.1.4)
NASA CountDown Clock Updated (NASA-CountDown 1.3.9.2)
Near Future Aeronautics (NearFutureAeronautics 2.1.0)
Near Future Construction (NearFutureConstruction 1.3.1)
Near Future Electrical (NearFutureElectrical 1.2.1)
Near Future Electrical - Decaying RTGs (NearFutureElectrical-DecayingRTGs 1.2.1)
Near Future Electrical Core (NearFutureElectrical-Core 1.2.1)
Near Future Exploration (NearFutureExploration 1.1.1)
Near Future IVA Props (NearFutureProps 1:0.6.4)
Near Future Launch Vehicles (NearFutureLaunchVehicles 2.1.2)
Near Future Propulsion (NearFuturePropulsion 1.3.1)
Near Future Propulsion - Xenon Hall Effect Thrusters (NearFuturePropulsion-XenonHETs 1.3.1)
Near Future Solar (NearFutureSolar 1.3.1)
Near Future Solar Core (NearFutureSolar-Core 1.3.1)
Near Future Spacecraft (NearFutureSpacecraft 1.4.1)
Near Future Spacecraft - LFO Engines (NearFutureSpacecraft-OrbitalLFOEngines 1.4.1)
Neptune Camera (NeptuneCamera v3.0)
New Tantares (NewTantares v23.2)
New TantaresLV (NewTantaresLV v14)
NovaPunch Rebalanced (NovaPunchRebalanced 0.1.7.1)
NovaPunchRebalanced Freyja (NovaPunchRebalanced-Freyja 0.1.7.1)
NovaPunchRebalanced Odin (NovaPunchRebalanced-Odin 0.1.7.1)
NovaPunchRebalanced Thor (NovaPunchRebalanced-Thor 0.1.7.1)
Omega's Stockalike Structures: No Textures Required (StockalikeStructures 0.0.12)
Orbit's US Flag Pack (OrbitsUSFlagPack 2)
Patch Manager (PatchManager 0.0.17.2)
Phoenix Industries (PhoenixIndustries 1.7)
Phoenix Industries EVA Survival Suit (PhoenixIndustriesEVASuit 1)
Phoenix Industries Flags (PhoenixIndustriesFlags 2.1)
PicoPort (PicoPort 0.1.6.3)
PicoPort for all sizes (PicoPort4AllSizes 0.1.2.3)
PicoPort Shielded (PicoPortShielded 1.0.1.1)
PlanetShine (PlanetShine 0.2.6.3)
PlanetShine - Default configuration (PlanetShine-Config-Default 0.2.6.3)
Polish Flag Pack (PolishFlagPack v1.2)
Probe Control Room Recontrolled (ProbeControlRoomRecontrolled 1.2.3)
Procedural Fairings (ProceduralFairings 1:v1.8.3)
'Project Orion' Nuclear Pulse Engine (USI-NuclearRockets 1.4.0)
Pure Electric Engines (PureElectricEngines 1:1.10.2)
RasterPropMonitor (RasterPropMonitor 1:v0.31.4)
RasterPropMonitor Core (RasterPropMonitor-Core 1:v0.31.4)
Real Plume (RealPlume 2:v13.3.2)
Real Plume - Stock Configs (RealPlume-StockConfigs v4.0.5)
Real Time Clock 2 (RealTimeClock2 v1.11.2)
RealChute Parachute Systems (RealChute v1.4.8.2)
Recoverable Emergency Kerbal Transport (REKT 0.4.8.2)
RecoveryController (RecoveryController 0.0.4)
Recycled Parts (RecycledParts 0.2.0.2)
RemoteTech Redev Antennas (RemoteTechRedevAntennas 0.1.1)
REPOSoftTech-Agencies (REPOSoftTech-Agencies V1.5.8.0)
ReStock (ReStock 1.3.1)
ReStock+ (ReStockPlus 1.3.1)
Retractable Lifting Surface Module (RetractableLiftingSurface 0.2.1.1)
RLA Reborn (RLAReborn 0.15.2)
RNMisc (RN-MiscParts 1:v1.6)
Rocket Emporium (RocketEmporium v1.8.5)
S.A.V.E (SAVE 1.10.2-3192)
Salyut Stations (RN-SalyutStations 1:v3.4)
SamBelanger Flags (SamBelangerFlags 1:v1.0)
Sarkomand Aeronautics Flag (Sarkomand v1.0)
SCANsat (SCANsat v20.4)
scatterer (Scatterer 3:v0.0723)
Scatterer Default Config (Scatterer-config 3:v0.0723)
Scatterer Sunflare (Scatterer-sunflare 3:v0.0723)
SDHI Strobe-O-Matic Warning Rotator Lights (SDHI-StrobeOMatic v1.0.1)
Shangsheng Orbital (ShangshengOrbital v0.4)
Ship Effects Continued (ShipEffectsContinued 1.0.11)
Ship Manifest (ShipManifest 6.0.2.0)
Show FPS (ShowFPS 1:0.2.4)
Signal Delay (SignalDelay v0.2.13)
Simple Adjustable Fairings - KW Rocketry Pack (SimpleAdjustableFairings-KWRocketry v1.3.0)
Simple Adjustable Fairings - Plugin (SimpleAdjustableFairings v1.11.0)
Skylab (RN-Skylab 1:v1.8.6)
Smart Parts (SmartParts 1.9.16)
SmokeScreen - Extended FX Plugin (SmokeScreen 2.8.14.0)
Solar Science (SolarScience 1:v1.2.0.0)
Soviet Probes (RN-SovietProbes 1:v2.9)
Soviet Rockets - R7/Proton/Zenit Rockets and more (RN-SovietRockets 2:v3.7)
Soviet Spacecraft - Soyuz, Progress, Vostok/Voskhod, TKS/VA (RN-SovietSpacecraft 1:v1.8.6)
Soyuz TMA and R7 (AbovetheSkySoyuzTMAandR7 v1.0.1)
Space Launch System Part Pack (SpaceLaunchSystemPartPack 1.9.1.2)
SpaceTux Library (SpaceTuxLibrary 0.0.5.2)
SpacetuxSA (SpacetuxSA 0.3.13.1)
SpaceX Launch Vehicles - Real Size (SpaceXLaunchVehicles 6.5)
SpaceY Expanded (SpaceY-Expanded 1.4)
SpaceY Heavy Lifters (SpaceY-Lifters 1.17.2)
Special Delivery - Stockalike Cygnus (SpecialDelivery 1.1)
Spherical and Toroidal Tank Pack (TALSphericalToroidalPack 3.12)
StarLink Satellite Pack (StarLinkSatellitePack 1.1.0)
Stational Cunstructs (StationalConstructs 1.8.1)
SteeringTweaker (SteeringTweaker 1.1)
Stockalike Station Parts Expansion Redux (StationPartsExpansionRedux 1.4.0)
Structural Disks (StructuralDisks 1.2.0.1)
Structural Tubing Restructured (StructuralTubing 1.0.8.1)
Sum Dum Heavy Industries - Service Module System (SDHI-ServiceModuleSystem v4.0.4)
Sum Dum Heavy Industries - Shared Assets (SDHI-SharedAssets 4.0.4)
SuperBattery (SuperBattery 1.2.3)
TantaresSP (TantaresSP 3.0)
Tarsier Space Technology with Galaxies Continued... (TarsierSpaceTechnologyWithGalaxies 1:7.11)
TDAPS (TDAdvancedPropulsionSystems 0.6.200606)
TextureReplacer (TextureReplacer v4.3.1)
Textures Unlimited (TexturesUnlimited 1.5.10.25)
The Janitor's Closet (JanitorsCloset 0.3.7)
The SSR MicroSat: 0.35m Probe Parts Revived (MicroSatRevived 0.1.3.2)
Tokamak Refurbished Parts (TokamakRefurbishedParts 0.2.0.2)
Toolbar (Toolbar 1:1.8.0.5)
Toolbar Controller (ToolbarController 1:0.1.9.4)
Tracking Station Evolved (TrackingStationEvolved 6.0)
Trajectories (Trajectories v2.4.0)
Triple-Z RadioTelescope (ZZZRadioTelescope 1.0.5)
Tundra Exploration - Stockalike Dragon V2 and Falcon 9 (TundraExploration 3.3.0)
Tundra Technologies (TundraTechnologies 3.3.0)
Tundra's Space Center (TundraSpaceCenter 2.0.1)
ULA Vulcan (ULAVulcan 1.2)
Universal Storage II (UniversalStorage2 1.9.1.2)
US Probes Pack (RN-USProbesPack 1:v0.78)
US Rockets (RN-USRockets 1:v0.9.7)
USI Core (USI-Core 1.4.0)
USI Tools (USITools 1.4.0)
VaporVent (VaporVent 1.1.11)
Vessel Viewer Continued (VesselView 2:0.8.8.3)
VesselView-UI-RasterPropMonitor (VesselView-UI-RasterPropMonitor 1:0.8.8.3)
VesselView-UI-Toolbar (VesselView-UI-Toolbar 1:0.8.8.3)
Vostok Continued (VostokContinued 1.1)
Waterfall - Restock (WaterfallRestock 0.1.5)
Waterfall Core (Waterfall 0.4.1)
Where Can I Go (WhereCanIGo 2.1)
Wild Blue Tools (WildBlueTools v1.82)
WildBlueIndustries CRP Play Mode (WildBlue-PlayMode-CRP v1.82)
WorldStabilizer (WorldStabilizer 0.9.7-ksp-1.8.1)
Xingyun-2 Satellite (Xingyun2 1.0)
Zero MiniAVC (ZeroMiniAVC 1:1.1.0.1)
                                    </pre>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php include 'parts/footer.php';?>

